
/* This file is generated using iocbio/analysis/src/generate_cf_source.py.

  Author: Pearu Peterson
  Created: Oct 2011
*/
#ifndef CF_H
#define CF_H

#ifdef __cplusplus
extern "C" {
#endif
extern void cf_a33_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs_diff2(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs_diff3(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs_diff4(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs_diff5(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs_diff6(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff6(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff6(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs_diff7(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme_diff7(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a33_find_zero_diff7(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a33_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_a33_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_a33_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_a33_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_a33_f1_evaluate(double x, double *f, int n, int order);
extern double cf_a33_f2_evaluate(double x, double *f, int n, int order);
extern void cf_a22_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_a22_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a22_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a22_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_a22_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a22_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a22_compute_coeffs_diff2(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_a22_find_extreme_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a22_find_zero_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a22_compute_coeffs_diff3(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_a22_find_extreme_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a22_find_zero_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a22_compute_coeffs_diff4(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_a22_find_extreme_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a22_find_zero_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a22_compute_coeffs_diff5(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_a22_find_extreme_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a22_find_zero_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a22_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_a22_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_a22_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_a22_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_a22_f1_evaluate(double x, double *f, int n, int order);
extern double cf_a22_f2_evaluate(double x, double *f, int n, int order);
extern void cf_e33_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs_diff2(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs_diff3(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs_diff4(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs_diff5(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs_diff6(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff6(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff6(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs_diff7(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme_diff7(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e33_find_zero_diff7(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e33_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5, double* a6, double* a7);
extern int cf_e33_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_e33_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_e33_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_e33_f1_evaluate(double x, double *f, int n, int order);
extern double cf_e33_f2_evaluate(double x, double *f, int n, int order);
extern void cf_e22_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_e22_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e22_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e22_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_e22_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e22_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e22_compute_coeffs_diff2(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_e22_find_extreme_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e22_find_zero_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e22_compute_coeffs_diff3(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_e22_find_extreme_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e22_find_zero_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e22_compute_coeffs_diff4(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_e22_find_extreme_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e22_find_zero_diff4(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e22_compute_coeffs_diff5(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_e22_find_extreme_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e22_find_zero_diff5(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e22_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1, double* a2, double* a3, double* a4, double* a5);
extern int cf_e22_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_e22_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_e22_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_e22_f1_evaluate(double x, double *f, int n, int order);
extern double cf_e22_f2_evaluate(double x, double *f, int n, int order);
extern void cf_e11_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_e11_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e11_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e11_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_e11_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e11_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e11_compute_coeffs_diff2(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_e11_find_extreme_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e11_find_zero_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e11_compute_coeffs_diff3(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_e11_find_extreme_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e11_find_zero_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e11_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1, double* a2, double* a3);
extern int cf_e11_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_e11_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_e11_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_e11_f1_evaluate(double x, double *f, int n, int order);
extern double cf_e11_f2_evaluate(double x, double *f, int n, int order);
extern void cf_a00_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1);
extern int cf_a00_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a00_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a00_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1);
extern int cf_a00_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a00_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a00_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1);
extern int cf_a00_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_a00_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_a00_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_a00_f1_evaluate(double x, double *f, int n, int order);
extern double cf_a00_f2_evaluate(double x, double *f, int n, int order);
extern void cf_e00_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1);
extern int cf_e00_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e00_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e00_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1);
extern int cf_e00_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_e00_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_e00_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1);
extern int cf_e00_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_e00_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_e00_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_e00_f1_evaluate(double x, double *f, int n, int order);
extern double cf_e00_f2_evaluate(double x, double *f, int n, int order);
extern void cf_a11_compute_coeffs_diff0(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_a11_find_extreme_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a11_find_zero_diff0(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a11_compute_coeffs_diff1(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_a11_find_extreme_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a11_find_zero_diff1(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a11_compute_coeffs_diff2(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_a11_find_extreme_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a11_find_zero_diff2(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a11_compute_coeffs_diff3(int j, double *fm, int n, int m, double* a0, double* a1, double* a2, double* a3);
extern int cf_a11_find_extreme_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern int cf_a11_find_zero_diff3(int j0, int j1, double *fm, int n, int m, double* result);
extern void cf_a11_compute_coeffs(int j, double *fm, int n, int m, int order, double* a0, double* a1, double* a2, double* a3);
extern int cf_a11_find_extreme(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern int cf_a11_find_zero(int j0, int j1, double *fm, int n, int m, int order, double* result);
extern double cf_a11_evaluate(double y, double *fm, int n, int m, int order);
extern double cf_a11_f1_evaluate(double x, double *f, int n, int order);
extern double cf_a11_f2_evaluate(double x, double *f, int n, int order);
extern void cf_quadratic_approximation_3_0(double a1_0, double a2_0, double a3_0, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_0(double a1_0, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_0(double a1_0, double a2_0, double a3_0, double* p0, double* p1);
extern void cf_linear_approximation_1_0(double a1_0, double* p0, double* p1);
extern void cf_quadratic_approximation_3_1(double a1_0, double a1_1, double a2_0, double a2_1, double a3_0, double a3_1, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_1(double a1_0, double a1_1, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_1(double a1_0, double a1_1, double a2_0, double a2_1, double a3_0, double a3_1, double* p0, double* p1);
extern void cf_linear_approximation_1_1(double a1_0, double a1_1, double* p0, double* p1);
extern void cf_quadratic_approximation_3_2(double a1_0, double a1_1, double a1_2, double a2_0, double a2_1, double a2_2, double a3_0, double a3_1, double a3_2, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_2(double a1_0, double a1_1, double a1_2, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_2(double a1_0, double a1_1, double a1_2, double a2_0, double a2_1, double a2_2, double a3_0, double a3_1, double a3_2, double* p0, double* p1);
extern void cf_linear_approximation_1_2(double a1_0, double a1_1, double a1_2, double* p0, double* p1);
extern void cf_quadratic_approximation_3_3(double a1_0, double a1_1, double a1_2, double a1_3, double a2_0, double a2_1, double a2_2, double a2_3, double a3_0, double a3_1, double a3_2, double a3_3, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_3(double a1_0, double a1_1, double a1_2, double a1_3, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_3(double a1_0, double a1_1, double a1_2, double a1_3, double a2_0, double a2_1, double a2_2, double a2_3, double a3_0, double a3_1, double a3_2, double a3_3, double* p0, double* p1);
extern void cf_linear_approximation_1_3(double a1_0, double a1_1, double a1_2, double a1_3, double* p0, double* p1);
extern void cf_quadratic_approximation_3_4(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_4(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_4(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double* p0, double* p1);
extern void cf_linear_approximation_1_4(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double* p0, double* p1);
extern void cf_quadratic_approximation_3_5(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a2_5, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double a3_5, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_5(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_5(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a2_5, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double a3_5, double* p0, double* p1);
extern void cf_linear_approximation_1_5(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double* p0, double* p1);
extern void cf_quadratic_approximation_3_6(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a2_5, double a2_6, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double a3_5, double a3_6, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_6(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_6(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a2_5, double a2_6, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double a3_5, double a3_6, double* p0, double* p1);
extern void cf_linear_approximation_1_6(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double* p0, double* p1);
extern void cf_quadratic_approximation_3_7(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double a1_7, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a2_5, double a2_6, double a2_7, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double a3_5, double a3_6, double a3_7, double* p0, double* p1, double* p2);
extern void cf_quadratic_approximation_1_7(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double a1_7, double* p0, double* p1, double* p2);
extern void cf_linear_approximation_3_7(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double a1_7, double a2_0, double a2_1, double a2_2, double a2_3, double a2_4, double a2_5, double a2_6, double a2_7, double a3_0, double a3_1, double a3_2, double a3_3, double a3_4, double a3_5, double a3_6, double a3_7, double* p0, double* p1);
extern void cf_linear_approximation_1_7(double a1_0, double a1_1, double a1_2, double a1_3, double a1_4, double a1_5, double a1_6, double a1_7, double* p0, double* p1);
extern double cf_find_real_zero_in_01_2(double a_0, double a_1, double a_2);

#ifdef __cplusplus
}
#endif
#endif
